---
name: bosh

releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.3
    sha1: e4442afcc64123e11f2b33cc2be799a0b59207d0
  - name: bosh-google-cpi
    url: https://storage.googleapis.com/bosh-cpi-artifacts/bosh-google-cpi-25.4.1.tgz
    sha1: 4dbc5c9611724eb270b510b96d5cbde9052f9c31

resource_pools:
  - name: vms
    network: private
    stemcell:
      url: https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.12-google-kvm-ubuntu-trusty-go_agent.tgz
      sha1: 0fadc768d0d262f3d5354872710c121aecbb6f15
    cloud_properties:
      zone: "((zone))"
      machine_type: n1-standard-4
      root_disk_size_gb: 40
      root_disk_type: pd-standard
      service_scopes:
        - compute
        - devstorage.full_control

disk_pools:
  - name: disks
    disk_size: 32_768
    cloud_properties:
      type: pd-standard

networks:
  - name: vip
    type: vip
  - name: private
    type: manual
    subnets:
    - range: 10.0.1.0/16
      gateway: 10.0.1.1
      static: [10.0.1.3-10.0.1.7]
      cloud_properties:
        network_name: cf-network
        subnetwork_name: cf-subnet
        ephemeral_external_ip: true
        tags:
          - bosh

jobs:
  - name: bosh
    instances: 1

    templates:
      - name: nats
        release: bosh
      - name: postgres
        release: bosh
      - name: blobstore
        release: bosh
      - name: director
        release: bosh
      - name: health_monitor
        release: bosh
      - name: google_cpi
        release: bosh-google-cpi

    resource_pool: vms
    persistent_disk_pool: disks

    networks:
      - name: private
        static_ips: [10.0.1.3]
        default:
          - dns
          - gateway
      - name: vip
        static_ips: ["((director_ip))"]

    properties:
      nats:
        address: 127.0.0.1
        user: nats
        password: "((nats_password))"

      postgres: &db
        listen_address: 127.0.0.1
        host: 127.0.0.1
        user: postgres
        password: "((postgres_password))"
        database: bosh
        adapter: postgres

      blobstore:
        address: 10.0.1.3
        port: 25250
        provider: dav
        director:
          user: director
          password: "((blobstore_director_password))"
        agent:
          user: agent
          password: "((blobstore_agent_password))"

      director:
        ssl:
          cert: "((director_cert))"
          key: "((director_key))"
        address: 127.0.0.1
        name: micro-google
        db: *db
        cpi_job: google_cpi
        user_management:
          provider: local
          local:
            users:
            - name: "((director_username))"
              password: "((director_password))"
            - name: hm
              password: "((hm_password))"
      hm:
        director_account:
          user: hm
          password: "((hm_password))"
        resurrector_enabled: true

      google: &google_properties
        project: "((project))"
        default_zone: "((zone))"
        json_key: "((google_cpi_json_key))"

      ntp: &ntp
        - 169.254.169.254

      agent:
        mbus: "nats://nats:((nats_password))@10.0.1.3:4222"
        ntp: *ntp
        blobstore:
           options:
             endpoint: http://10.0.1.3:25250
             user: agent
             password: "((blobstore_agent_password))"

cloud_provider:
  template:
    name: google_cpi
    release: bosh-google-cpi

  ssh_tunnel:
    port: 22
    user: vcap
    host: "((director_ip))"
    private_key: "((director_ssh_key_path))"

  mbus: "https://mbus:((mbus_password))@((director_ip)):6868"

  properties:
    google: *google_properties
    agent: {mbus: "https://mbus:((mbus_password))@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
